apiVersion: apps/v1
	kind: Deployment
	metadata:
	  name: spring-postgress
	spec:
	  replicas: 1
	  selector:
	    matchLabels:
	      app: spring-postgress
	  template:
	    metadata:
	      labels:
	        app: spring-postgress
	    spec:
	      imagePullSecrets:
	      - name: ghcr-credentials
	      containers:
	      - name: spring-postgress
	        image: ghcr.io/springboot-postgres:dev-ft-0.0.1     
	        imagePullPolicy: Always
	        ports:
	        - containerPort: 80
	        readinessProbe:
	          httpGet:
	            path: /
	            port: 80
	          initialDelaySeconds: 5
	          periodSeconds: 5
	