---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 5
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /test
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-postgres-lb
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"my-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: spring-postgress
  ports:
    - name: spring-postgres-svc
      port: 80
      targetPort: 8080
  # type: LoadBalancer